### ISSUE TITLE
bug/UIManager 한글 코드 깨짐

### ISSUE THREAD

**Issue by yarogono** [homebd/nbcamp_A10#10]
# UIManager 한글 깨짐 이슈
- UIManagers.cs SetNumCanvas()에 한글로 하드코딩 되어 있는 곳
- 한글로 입력된 코드가 깨져서 UI에 렌더링 되는 문제

**Comment by jhwan328** [comment]
글자 깨지는 경우에 대해서 검색해보고 있는데 서로 사용하는 폰트가 다를 경우 그럴 수 있다고 하더라고요.
그래서 텍스트에 Asset에 있는 폰트를 적용해서 다시 Push 했습니다.
