### ISSUE TITLE
bug/빠른 매칭 성공 시 게임 미완료

### ISSUE THREAD

**Issue by homebd** [homebd/nbcamp_A10#14]
카드가 4장 남았다고 가정했을 때,
2장을 지우고 해당 카드가 지워지기 전에
나머지 2장을 매칭하면 매칭한 당시에는 카드가 4장 남아있기 때문에 종료 조건은 달성되지 않고
남은 카드가 0장이 됩니다.

**Comment by homebd** [comment]
이건 cardleft를 IsMatched에서 비교하는 대신
Update에서 0인지 비교하는 방식으로 고치면 어떤가요?

**Comment by jhwan328** [comment]
아예 cardleft를 Cardmanager의 Start에서 선언하고 Destroycard가 호출할 때마다 -1 을 하는 건 어떨까요?

**Comment by jhwan328** [comment]
`이런 식으로요`

```csharp
 firstCard.GetComponent<Card>().DestroyCard();
            cardsLeft--;
            secondCard.GetComponent<Card>().DestroyCard();
            cardsLeft--;
            if(cardsLeft == 0) {
               GameManager.I.uiManager.ActiveEndText();
            }
```

**Comment by homebd** [comment]
좋은 방법인 것 같아요
cardsLeft를 미리 선언만 해두고 Generate 단계에서 초기화해줘도 될 거 같네요!

**Comment by jhwan328** [comment]
`다만 게임 매니저에서`

```csharp
if(cardManager != null) {
      cardManager.GenerateCard();
}
```

'Start 안에 들어있는 이 부분에서 카드를 생성하니 '
int cardsLeft = GameObject.Find("Cards").transform.childCount;
'이 부분만 GenerateCard() 다음으로 호출되게 하면 될 거 같아요'

**Comment by jhwan328** [comment]
네 정확히 그 말이예요!
